//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "OcrCapturedImage.xaml.h"

void ::SDKTemplate::OcrCapturedImage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///OcrCapturedImage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SDKTemplate::OcrCapturedImage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->StatusBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 4:
        {
            this->ExtractButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ExtractButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SDKTemplate::OcrCapturedImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OcrCapturedImage::ExtractButton_Tapped);
        }
        break;
    case 5:
        {
            this->CameraButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CameraButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SDKTemplate::OcrCapturedImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OcrCapturedImage::CameraButton_Tapped);
        }
        break;
    case 6:
        {
            this->PreviewControl = safe_cast<::Windows::UI::Xaml::Controls::CaptureElement^>(__target);
        }
        break;
    case 7:
        {
            this->ImageGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 8:
        {
            this->PreviewImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PreviewImage))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::SDKTemplate::OcrCapturedImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&OcrCapturedImage::PreviewImage_SizeChanged);
        }
        break;
    case 9:
        {
            this->TextOverlay = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SDKTemplate::OcrCapturedImage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


