//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "OcrFileImage.xaml.h"

void ::SDKTemplate::OcrFileImage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///OcrFileImage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SDKTemplate::OcrFileImage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->LanguageList = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->LanguageList))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&OcrFileImage::LanguageList_SelectionChanged);
        }
        break;
    case 4:
        {
            this->Image = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 5:
        {
            this->ExtractedTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 6:
        {
            this->SampleButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->SampleButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OcrFileImage::SampleButton_Tapped);
        }
        break;
    case 7:
        {
            this->LoadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->LoadButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OcrFileImage::LoadButton_Tapped);
        }
        break;
    case 8:
        {
            this->ExtractButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ExtractButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OcrFileImage::ExtractButton_Tapped);
        }
        break;
    case 9:
        {
            this->PreviewImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PreviewImage))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&OcrFileImage::PreviewImage_SizeChanged);
        }
        break;
    case 10:
        {
            this->TextOverlay = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 11:
        {
            this->UserLanguageToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->UserLanguageToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKTemplate::OcrFileImage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&OcrFileImage::UserLanguageToggle_Toggled);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SDKTemplate::OcrFileImage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


